<?php get_header(); ?>
	<div class="container">
		<div class="well">
			<div class="row-fluid">
							<p>The following terms and conditions govern all use of the SeedProd website and all content, services and products available at or through the website.</p>
							<p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by SeedProd, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>
							<ol>
							<li><strong>Plugin Licence.</strong>&nbsp; All plugins on SeedProd are&nbsp;licensed under the <a href="http://www.gnu.org/licenses/gpl-2.0.html#TOC1">GLP V2</a>.</li>
							<li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided “as is”. SeedProd and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither SeedProd nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted.&nbsp;You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li>
							<li class="important"><strong>Limitation of Liability.</strong> In no event will SeedProd, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to SeedProd under this agreement during the twelve (12) month period prior to the cause of action. SeedProd shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li>
							<li><strong>General Representation and Warranty.</strong> You represent and warrant that (i) your use of the Website will be in strict accordance with the SeedProd Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li>
							<li><strong>Indemnification.</strong> You agree to indemnify and hold harmless SeedProd, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</li>
							<li><strong>Miscellaneous.</strong> This Agreement constitutes the entire agreement between SeedProd and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of SeedProd, or by the posting by SeedProd of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of South Carolina, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in San Francisco County, California. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in Charleston, South Carolina, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; SeedProd may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</li>
							</ol>




			</div><!--/row -->
		</div>
	</div><!-- /container -->
<?php get_footer(); ?>